language: node_js
node_js:
  - "0.12"
env:
  global:
    - secure: RhmfgnPkrCcjOTWkfYFZS5zlBQhte2cAAtjA/bIKH4qhaLsWHHS0ApJ065PJs4H/lfslWSfnRcUpaeFq8hhr/9dMlCxFJc5CTJ2EfmV56NjsiaETtrxHdNVFtZU/DxJnSxnW4revbFkk/mM6JZ+P7XwVv+iitKhx3uRpX2/rKWA=
    - secure: hmu/VH1viA8oPFjxBrjvnLrNa0PnfXsIKMMv9ZmgpXthdhTtuReD9rPmbnFzNh9MyCkLSZcndJakpDu9SwHVDcs5eyV72fuXHW/0htyN9eNTMyShrNIpOJe6JUqMez7MxQU9J45IJGSvbyEfrbZ20mbGGzJ41KnEZ0IfwODPcMY=
    - secure: lDZ7z1MCEq7j+jXZUGMjZ08nUiFlCQJ9BuO8t2mp3C0+glCYxebL3W9MEV5UCiW41G2EOBnYCa7WJ6prJgDKKILmqSdIm/Z0wNrwt/hXbAcwy6QOMtbX4PSnTkOpY3tDqkFR2I3OddKtzEpHr2ch0rAeKuYNf29CsT8YeH6vw1Fbj7hBG84sMVym1VSZlxlvTTSlUGO9Mk9PVqaBjq02wEKAmszARpfrrZtA+K+lMw8xco1JFoXrO7inohOZwiaMZeujd8f5F8ehbIJYb8ZqiPlR2JeDJUUGm8qawcvpb0zp0/8ftPi23IHNeJlw6OFo76O2AJFrr/Co76b4HW8Z83Lw3P82fR7uosS7wm21RfjdE1ymyCKYfBfU21yBhJGfcpXkpBlA87ngTpZF9a1VfD1aY5OR/ZViTqdwyR1l7LxyZGzSSldBE0hFp1cfJbRM6C/IancUXgbkoKWmkIDHItT6EReWWnoKGycln5VGy2nxs6h2d4si1RCCrHO1RgBh6xP+dvhJzMcDzENNKeb+7Fjic3Wy7T0n0mem8Ah8NhClCqnkkazCJVJyOo4nEMn5h7Tgya7okbDsWa7Us0voMVCq1f3pidHZU99mKyr+JT2q9EI+gSyd7b0w3kSTOQNBIr47lwa1fv530VRUknePV9C1efBOqnb/bBIOjPxwq6I=
    - secure: GC1FxEapbbu6ownKbJ4iHqG3Itg+qfKWEobtSDL55VEm1gHMOCScCwTYE/Is1Ekkfne3O6pqTf/mb6VlS++VEIDuCXTnvFrjnhvjDQSr66IrxL7SQxPEEXTl6xT71Xhc616Cf6aTO/a0jJRCHkSqs8HBo2Y7TpIrT9WAUAqo4pNDWN1IUmdp+3FleEJk+7iaFNUxthqu5gOYWnXXfLc/Qx1JSb2QTFBR0oEnaG60dpvWTvW3U0VZgHW2jNohLD0VHmzQNM2VQi4adRqgWSYkguCx4IjxLHKe1onymSG2b0rxStP9rBnbgJfsMgwTeHbGzinn/RIWBjam7mYRLYi6Px3gf3+Bhjfj12iT64qd5wqbadL9QZ5oANhE/91lUfkqzAFK/UBrSBivqK3itvqUfcT4rCF9Ne5Pzt3r3roSCwDox5k6zy6u26hU06V9ijp0eHxg4VsRAjF3yuNJMRQ+2wRDZlJo878fSt5T3UQS/LxoUc/sHjyetBcnW5hKpo2tE0EkuYAJBjAPRIpcEjppGpyRCSPS0TtclMxY+mwwUdXfup9Fsm3avALcHOKUd/FBgqOQveNtjefPW2xKS5HNA5dFaCUrbL2QUsnm+1ovIVv+e0JNilkcJkL11Znfo9gt/8sdDESW1ZtKRzxvV5A5Ezoi0WoK5h+8aMou5P7NLRY=
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - npm install
script:
  - grunt test:development
  - grunt test
  - grunt e2e --ci
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
addons:
  sauce_connect: true
